/**
 * Service lifecycle — install / uninstall / update tired-agent as a managed
 * OS service, plus delegation hooks so start/stop/restart/status can route
 * through the platform supervisor.
 *
 * Platform matrix:
 *   - linux  → systemd user unit (~/.config/systemd/user/tired-agent.service)
 *   - darwin → launchd LaunchAgent (~/Library/LaunchAgents/com.tiredagent.agent.plist)
 *   - win32  → not yet supported (scheduled-task plan; guidance only)
 *   - other  → unsupported
 *
 * Notes:
 *   - The service command is <node> <realpath(cli)> start so upgrades via
 *     `npm i -g` (which overwrites in place) keep the unit valid.
 *   - install never auto-kills a process holding our port — it may be hosting
 *     the very session running the CLI (e.g. the agent's own PTY). It warns
 *     instead and lets the user cut over.
 *   - All destructive operations accept --dry-run to preview commands.
 */

import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync, unlinkSync } from 'node:fs';
import { spawnSync, type SpawnSyncReturns } from 'node:child_process';

export const SERVICE_NAME = 'tired-agent';
const DARWIN_LABEL = 'com.tiredagent.agent';
const DEFAULT_DATA_DIR = join(homedir(), '.tiredagent');

// ── platform helpers ──────────────────────────────────────────────────

export type ServicePlatform = 'linux' | 'darwin' | 'win32' | 'unsupported';

export function detectPlatform(): ServicePlatform {
  if (process.platform === 'linux') return 'linux';
  if (process.platform === 'darwin') return 'darwin';
  if (process.platform === 'win32') return 'win32';
  return 'unsupported';
}

export function serviceConfigPath(): string {
  if (process.platform === 'linux') {
    return join(homedir(), '.config', 'systemd', 'user', `${SERVICE_NAME}.service`);
  }
  if (process.platform === 'darwin') {
    return join(homedir(), 'Library', 'LaunchAgents', `${DARWIN_LABEL}.plist`);
  }
  return '';
}

export function isServiceInstalled(): boolean {
  const p = serviceConfigPath();
  if (!p) return false;
  try {
    return existsSync(p);
  } catch {
    return false;
  }
}

function uid(): string {
  const u = typeof process.getuid === 'function' ? process.getuid() : undefined;
  return u != null ? String(u) : process.env['UID'] ?? '501';
}

// ── process execution ─────────────────────────────────────────────────

interface CmdResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

function run(cmd: string, args: string[]): CmdResult {
  let r: SpawnSyncReturns<string>;
  try {
    r = spawnSync(cmd, args, { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (err) {
    return { status: 1, stdout: '', stderr: String((err as Error).message) };
  }
  return { status: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

/** Exec wrapper honouring --dry-run: prints the command instead of running it. */
function exec(ctx: { dryRun: boolean }, cmd: string, args: string[]): CmdResult {
  if (ctx.dryRun) {
    console.log(`  [dry-run] ${cmd} ${args.join(' ')}`);
    return { status: 0, stdout: '', stderr: '' };
  }
  const r = run(cmd, args);
  if (r.status !== 0 && r.stderr.trim()) console.error(r.stderr.trim());
  return r;
}

// ── config generation (pure, unit-testable) ───────────────────────────

/** Resolve the service command: <node> <realpath(cli.js)> start [--register …]. */
export function buildProgramArgs(registerBase64?: string): string[] {
  const script = realpathSync(process.argv[1] ?? process.execPath);
  const args = [process.execPath, script, 'start'];
  if (registerBase64) args.push('--register', registerBase64);
  return args;
}

export function buildSystemdUnit(programArgs: string[], _registerBase64?: string): string {
  const cmd = programArgs.join(' ');
  return `# Generated by \`tired-agent install service\`. Re-run install to regenerate.
# Runs the agent in the foreground; systemd supervises it (auto-restart on
# crash, start on boot via linger). Config comes from ~/.tiredagent/.env.
[Unit]
Description=tired-agent PTY executor daemon

[Service]
Type=simple
ExecStart=${cmd}

Restart=always
RestartSec=3
TimeoutStopSec=15
KillSignal=SIGTERM

[Install]
WantedBy=default.target
`;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function buildLaunchdPlist(programArgs: string[], dataDir: string): string {
  const args = programArgs.map((a) => `    <string>${escapeXml(a)}</string>`).join('\n');
  const logDir = join(dataDir, 'logs');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${DARWIN_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>${escapeXml(dataDir)}</string>
  <key>StandardOutPath</key>
  <string>${escapeXml(join(logDir, 'launchd.out.log'))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(join(logDir, 'launchd.err.log'))}</string>
</dict>
</plist>
`;
}

function resolveDataDir(explicit?: string): string {
  return explicit ? resolve(explicit) : resolve(process.env['CLSSW_DATA'] ?? DEFAULT_DATA_DIR);
}

// ── linux helpers ─────────────────────────────────────────────────────

function readPortFromEnv(dataDir: string): number {
  try {
    const dotenv = readFileSync(join(dataDir, '.env'), 'utf-8');
    const m = dotenv.match(/^PORT=(.+)$/m);
    if (m?.[1]) {
      const n = Number.parseInt(m[1].trim(), 10);
      if (Number.isFinite(n)) return n;
    }
  } catch {
    /* .env missing — fall back to default */
  }
  return 8444;
}

/** Find who listens on `port` (via `ss -ltnp`) and whether it's our service. */
function findListener(port: number): { pid: number; isService: boolean } | null {
  const r = run('ss', ['-ltnp']);
  if (r.status !== 0) return null; // ss unavailable — skip conflict detection
  const line = r.stdout.split('\n').find((l) => new RegExp(`:${port}\\s`).test(l));
  if (!line) return null;
  const m = line.match(/pid=(\d+)/);
  if (!m) return null;
  const pid = Number(m[1]);
  let isService = false;
  try {
    isService = readFileSync(`/proc/${pid}/cgroup`, 'utf-8').includes(`${SERVICE_NAME}.service`);
  } catch {
    /* ignore */
  }
  return { pid, isService };
}

// ── lifecycle commands ────────────────────────────────────────────────

export interface InstallOptions {
  registerBase64?: string;
  dryRun?: boolean;
  dataDir?: string;
}

export function installService(opts: InstallOptions): number {
  const ctx = { dryRun: !!opts.dryRun };
  const plat = detectPlatform();
  const programArgs = buildProgramArgs(opts.registerBase64);
  const dataDir = resolveDataDir(opts.dataDir);

  if (plat === 'linux') return installLinux(ctx, programArgs, dataDir);
  if (plat === 'darwin') return installDarwin(ctx, programArgs, dataDir);
  if (plat === 'win32') {
    console.log('Windows service startup is not supported yet.');
    console.log('  A scheduled-task (schtasks) approach is planned; OpenClaw also has no service startup.');
    console.log('  For now run in the background with: tired-agent start -D');
    console.log('  or manage manually with nssm (see packages/agent/service/install-service.ps1).');
    return 0;
  }
  console.error(`Unsupported platform "${process.platform}". Supported: linux (systemd), darwin (launchd).`);
  return 1;
}

function installLinux(ctx: { dryRun: boolean }, programArgs: string[], dataDir: string): number {
  const unitPath = serviceConfigPath();
  const unit = buildSystemdUnit(programArgs);

  if (ctx.dryRun) {
    console.log(`Would write ${unitPath}:`);
    console.log(unit.trim());
    console.log('Then run:');
    console.log('  systemctl --user daemon-reload');
    console.log('  systemctl --user enable --now tired-agent');
    return 0;
  }

  const sysd = run('systemctl', ['--user', 'is-system-running']);
  if (sysd.status !== 0) {
    console.error('User systemd instance is not available (systemctl --user failed).');
    console.error('Is systemd running? Check: systemctl --user is-system-running');
    return 1;
  }

  mkdirSync(join(homedir(), '.config', 'systemd', 'user'), { recursive: true });
  writeFileSync(unitPath, unit, 'utf-8');
  console.log(`Wrote ${unitPath}`);

  // Port conflict detection — never auto-kill: the holder may be hosting us.
  const port = readPortFromEnv(dataDir);
  const listener = findListener(port);
  let blocked = false;
  if (listener && !listener.isService) {
    console.warn(`Port ${port} is already held by PID ${listener.pid} (not the systemd service).`);
    console.warn('The service will fail to bind until it is stopped.');
    console.warn(`Run \`tired-agent stop\` to stop the old daemon, then \`systemctl --user restart tired-agent\`.`);
    blocked = true;
  } else if (listener && listener.isService) {
    console.log(`Port ${port} is already served by the tired-agent service — idempotent reinstall.`);
  }

  exec(ctx, 'systemctl', ['--user', 'daemon-reload']);
  if (blocked) {
    console.log('Unit installed but NOT started (port conflict). Cut over when ready:');
    console.log('  tired-agent stop');
    console.log('  systemctl --user restart tired-agent');
  } else {
    const e = exec(ctx, 'systemctl', ['--user', 'enable', '--now', SERVICE_NAME]);
    if (e.status !== 0) {
      console.error(`Failed to enable/start service. Check: journalctl --user -u ${SERVICE_NAME} -n 50`);
      return 1;
    }
  }

  // Boot-without-login autostart (needs linger; may require root on some distros).
  const user = process.env['USER'] ?? process.env['LOGNAME'] ?? '';
  const linger = exec(ctx, 'loginctl', ['enable-linger', user]);
  if (linger.status !== 0) {
    console.warn('Could not enable linger — the service will only auto-start after login.');
    console.warn(`Run once with root: sudo loginctl enable-linger ${user || '<your-user>'}`);
  }

  console.log();
  console.log('Done. Manage with:');
  console.log(`  systemctl --user status  ${SERVICE_NAME}`);
  console.log(`  systemctl --user restart ${SERVICE_NAME}`);
  console.log(`  journalctl --user -u ${SERVICE_NAME} -f`);
  return 0;
}

function installDarwin(ctx: { dryRun: boolean }, programArgs: string[], dataDir: string): number {
  const plistPath = serviceConfigPath();
  const plist = buildLaunchdPlist(programArgs, dataDir);
  const label = DARWIN_LABEL;
  const domain = `gui/${uid()}`;

  if (ctx.dryRun) {
    console.log(`Would write ${plistPath}:`);
    console.log(plist.trim());
    console.log('Then run:');
    console.log(`  launchctl bootstrap ${domain} ${plistPath}`);
    console.log(`  launchctl enable ${domain}/${label}`);
    return 0;
  }

  mkdirSync(join(dataDir, 'logs'), { recursive: true });
  mkdirSync(join(homedir(), 'Library', 'LaunchAgents'), { recursive: true });
  writeFileSync(plistPath, plist, 'utf-8');
  console.log(`Wrote ${plistPath}`);

  if (run('launchctl', ['print', `${domain}/${label}`]).status === 0) {
    console.log('LaunchAgent already loaded — re-enabling.');
    exec(ctx, 'launchctl', ['enable', `${domain}/${label}`]);
    exec(ctx, 'launchctl', ['kickstart', '-k', `${domain}/${label}`]);
  } else {
    const b = exec(ctx, 'launchctl', ['bootstrap', domain, plistPath]);
    if (b.status !== 0) {
      console.error(`launchctl bootstrap failed. Check: launchctl print ${domain}/${label}`);
      return 1;
    }
    exec(ctx, 'launchctl', ['enable', `${domain}/${label}`]);
  }

  console.log();
  console.log('Done. The agent runs in your login session (LaunchAgent), auto-start on login + crash-restart.');
  console.log('  For boot-without-login, install a LaunchDaemon instead (needs sudo):');
  console.log(`    sudo cp ${plistPath} /Library/LaunchDaemons/${label}.plist`);
  console.log(`    sudo launchctl bootstrap system /Library/LaunchDaemons/${label}.plist`);
  console.log('Manage with:');
  console.log(`  launchctl print ${domain}/${label}`);
  console.log(`  launchctl kickstart -k ${domain}/${label}`);
  return 0;
}

export interface UninstallOptions {
  dryRun?: boolean;
  purge?: boolean;
  dataDir?: string;
}

export function uninstallService(opts: UninstallOptions): number {
  const ctx = { dryRun: !!opts.dryRun };
  const plat = detectPlatform();

  if (!isServiceInstalled()) {
    console.log('tired-agent is not installed as a service.');
    return 0;
  }

  if (plat === 'linux') {
    exec(ctx, 'systemctl', ['--user', 'stop', SERVICE_NAME]);
    exec(ctx, 'systemctl', ['--user', 'disable', SERVICE_NAME]);
    const unitPath = serviceConfigPath();
    if (ctx.dryRun) {
      console.log(`  [dry-run] rm ${unitPath}`);
    } else {
      try { unlinkSync(unitPath); console.log(`Removed ${unitPath}`); } catch { /* already gone */ }
    }
    exec(ctx, 'systemctl', ['--user', 'daemon-reload']);
  } else if (plat === 'darwin') {
    const label = DARWIN_LABEL;
    exec(ctx, 'launchctl', ['bootout', `gui/${uid()}/${label}`]);
    const plistPath = serviceConfigPath();
    if (ctx.dryRun) {
      console.log(`  [dry-run] rm ${plistPath}`);
    } else {
      try { unlinkSync(plistPath); console.log(`Removed ${plistPath}`); } catch { /* already gone */ }
    }
  } else if (plat === 'win32') {
    console.log('Windows service startup is not supported yet; nothing to uninstall.');
    return 0;
  } else {
    console.error(`Unsupported platform "${process.platform}".`);
    return 1;
  }

  if (opts.purge) {
    const dataDir = resolveDataDir(opts.dataDir);
    if (ctx.dryRun) {
      console.log(`  [dry-run] rm -rf ${dataDir}`);
    } else {
      const looksLikeAgent =
        /tiredagent|tired-agent/.test(resolve(dataDir)) ||
        existsSync(join(dataDir, 'tired-agent.db.sqlite')) ||
        existsSync(join(dataDir, '.env'));
      if (!looksLikeAgent) {
        console.error(`Refusing to purge ${dataDir} — does not look like a tired-agent data dir.`);
        return 1;
      }
      const rm = run('rm', ['-rf', dataDir]);
      if (rm.status === 0) console.log(`Removed data directory ${dataDir}`);
      else console.error(`Failed to remove ${dataDir}: ${rm.stderr.trim()}`);
    }
  } else {
    console.log('Data directory kept (use --purge to also remove it).');
  }
  console.log('Service uninstalled.');
  return 0;
}

export interface UpdateOptions {
  version?: string;
  dryRun?: boolean;
}

export function updateService(opts: UpdateOptions): number {
  const ctx = { dryRun: !!opts.dryRun };
  const plat = detectPlatform();

  if (!isServiceInstalled()) {
    console.error('tired-agent is not installed as a service. Run `tired-agent install service` first.');
    return 1;
  }
  if (plat === 'win32') {
    console.log('Windows service startup is not supported yet; nothing to update.');
    return 0;
  }
  if (plat !== 'linux' && plat !== 'darwin') {
    console.error(`Unsupported platform "${process.platform}".`);
    return 1;
  }

  const target = opts.version ?? 'latest';
  const npm = exec(ctx, 'npm', ['install', '-g', `@tired-agent/agent@${target}`]);
  if (npm.status !== 0) {
    console.error(`npm install -g @tired-agent/agent@${target} failed.`);
    return 1;
  }

  // Regenerate the service config so it tracks the (possibly moved) binary.
  const programArgs = buildProgramArgs();
  if (plat === 'linux') {
    writeServiceConfig(serviceConfigPath(), buildSystemdUnit(programArgs), ctx);
    exec(ctx, 'systemctl', ['--user', 'daemon-reload']);
    const r = exec(ctx, 'systemctl', ['--user', 'restart', SERVICE_NAME]);
    if (r.status !== 0) return 1;
  } else {
    const dataDir = resolveDataDir();
    writeServiceConfig(serviceConfigPath(), buildLaunchdPlist(programArgs, dataDir), ctx);
    const r = exec(ctx, 'launchctl', ['kickstart', '-k', `gui/${uid()}/${DARWIN_LABEL}`]);
    if (r.status !== 0) return 1;
  }

  console.log('Service restarted with the updated package.');
  return 0;
}

function writeServiceConfig(path: string, content: string, ctx: { dryRun: boolean }): void {
  if (ctx.dryRun) {
    console.log(`  [dry-run] write ${path}`);
    return;
  }
  mkdirSync(resolve(path, '..'), { recursive: true });
  writeFileSync(path, content, 'utf-8');
  console.log(`Wrote ${path}`);
}

// ── delegation hooks (used by start/stop/restart/status when installed) ─

export function delegateServiceCommand(action: 'start' | 'stop' | 'restart'): number {
  const plat = detectPlatform();
  if (plat === 'linux') {
    return exec({ dryRun: false }, 'systemctl', ['--user', action, SERVICE_NAME]).status ?? 1;
  }
  if (plat === 'darwin') {
    const domain = `gui/${uid()}/${DARWIN_LABEL}`;
    const cmd =
      action === 'restart' ? ['kickstart', '-k', domain]
      : action === 'start' ? ['kickstart', domain]
      : ['bootout', domain];
    return exec({ dryRun: false }, 'launchctl', cmd).status ?? 1;
  }
  return 1;
}

export function printServiceStatus(): void {
  const plat = detectPlatform();
  if (plat === 'linux') {
    const r = run('systemctl', ['--user', 'status', SERVICE_NAME, '--no-pager']);
    console.log(r.stdout.trim());
    if (r.status !== 0) console.error(r.stderr.trim());
    return;
  }
  if (plat === 'darwin') {
    const r = run('launchctl', ['print', `gui/${uid()}/${DARWIN_LABEL}`]);
    console.log(r.stdout.trim() || r.stderr.trim());
    return;
  }
  console.log(`Service status is not supported on "${process.platform}".`);
}
