/**
 * Agent auto-registration with a Manager.
 *
 * Flow:
 *   1. Admin clicks "Generate registration command" in the onboarding UI.
 *   2. Manager issues a one-shot ticket (5 min TTL).
 *   3. UI builds base64(json({managerUrl, agentName, ticket})) and shows it.
 *   4. Agent startup decodes the string, POSTs to the Manager's
 *      registration endpoint with `Authorization: Bearer <ticket>`.
 *   5. Manager validates the ticket, registers the agent (or updates
 *      the existing row by agentKey), returns an agent-specific token.
 *   6. Agent persists the token + agentKey locally so subsequent restarts
 *      skip registration.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { networkInterfaces } from 'node:os';
import type { ServerConfig } from './config.js';

// ─── Types ──────────────────────────────────────────────────────

export interface RegisterPayload {
  managerUrl: string;
}

/**
 * Persisted credentials stored in `.agent-credentials`.
 *
 * - `agentKey` — generated by the agent once; used for dedup on
 *   re-registration (the manager stores this as `agent_key`).
 * - `id` — manager-assigned primary key.
 * - `token` — manager-assigned API token.
 */
export interface AgentCredentials {
  agentKey: string;
  id: string;
  token: string;
}

// ─── Registration logic ─────────────────────────────────────────

/** Decode a base64 register string. */
export function decodeRegisterString(b64: string): RegisterPayload {
  const json = Buffer.from(b64, 'base64').toString('utf-8');
  return JSON.parse(json) as RegisterPayload;
}

/** Path to the credentials file in the data directory. */
function credentialsPath(dataDir: string): string {
  return join(dataDir, '.agent-credentials');
}

/** Load saved credentials, if any. */
export async function loadCredentials(dataDir: string): Promise<AgentCredentials | null> {
  const file = credentialsPath(dataDir);
  if (!existsSync(file)) return null;
  try {
    const raw = await readFile(file, 'utf-8');
    return JSON.parse(raw) as AgentCredentials;
  } catch {
    return null;
  }
}

/** Persist credentials for subsequent restarts. */
export async function saveCredentials(dataDir: string, creds: AgentCredentials): Promise<void> {
  await mkdir(dataDir, { recursive: true });
  await writeFile(credentialsPath(dataDir), JSON.stringify(creds, null, 2), 'utf-8');
}

/**
 * Register this agent with the Manager.
 *
 * POSTs the agent's name, self-reported URL, and (on re-registration) the
 * persistent agentKey for dedup. Returns the assigned agent id and API token.
 */
export async function registerWithManager(
  managerUrl: string,
  name: string,
  agentBaseUrl: string,
  agentKey?: string,
): Promise<{ id: string; token: string }> {
  const base = managerUrl.replace(/\/+$/, '');
  const url = `${base}/v1/manager/agents/register`;

  const body: Record<string, string> = {
    name,
    baseUrl: agentBaseUrl,
  };
  if (agentKey) body.agentKey = agentKey;

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`registration failed (${res.status}): ${text}`);
  }

  return res.json() as Promise<{ id: string; token: string }>;
}

/**
 * Run the registration flow if needed.
 *
 * Checks for saved credentials first; if they exist, returns them
 * immediately.  Otherwise, if cfg.registerString is present, decodes
 * it and registers with the Manager.  Returns null if neither
 * condition is met.
 */
export async function getOrRegisterCredentials(cfg: ServerConfig): Promise<AgentCredentials | null> {
  // 1. Load any previously-saved credentials.
  const saved = await loadCredentials(cfg.dataDir);

  // 2. If a register string is present, always re-register (the manager
  //    may need an updated URL or token).  Pass the agentKey for dedup.
  if (cfg.registerString) {
    const agentKey = saved?.agentKey ?? randomUUID();
    const payload = decodeRegisterString(cfg.registerString);
    // When host is 0.0.0.0 (listen-all), resolve the first non-loopback
    // IPv4 so the manager can actually reach us.
    const advertiseHost = cfg.host === '0.0.0.0' ? detectLanIp() : cfg.host;
    const agentBaseUrl = `http://${advertiseHost}:${cfg.port}`;
    const creds = await registerWithManager(
      payload.managerUrl,
      cfg.name,
      agentBaseUrl,
      agentKey,
    );
    await saveCredentials(cfg.dataDir, { agentKey, id: creds.id, token: creds.token });
    return { agentKey, id: creds.id, token: creds.token };
  }

  // 3. No register string — use saved credentials if available.
  if (saved) return saved;

  return null;
}

/**
 * Detect the first non-loopback IPv4 address of this machine.
 * Used when the agent binds to `0.0.0.0` and needs to tell the
 * manager a reachable address.
 */
export function detectLanIp(): string {
  const interfaces = networkInterfaces();
  const candidates: string[] = [];
  for (const iface of Object.values(interfaces)) {
    if (!iface) continue;
    for (const addr of iface) {
      if (addr.family === 'IPv4' && !addr.internal) {
        candidates.push(addr.address);
      }
    }
  }
  // Prefer common private ranges.
  for (const ip of candidates) {
    if (ip.startsWith('192.168.') || ip.startsWith('10.') || ip.startsWith('172.')) {
      return ip;
    }
  }
  return candidates[0] ?? '127.0.0.1';
}
