/**
 * Agent auto-registration with a Manager.
 *
 * Flow:
 *   Admin generates base64(json({managerUrl, agentName, registerSecret})).
 *   Agent startup decodes the string, POSTs to the Manager's registration
 *   endpoint, receives an agent-specific token, and persists it locally
 *   so subsequent restarts skip registration.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { ServerConfig } from './config.js';

// ─── Types ──────────────────────────────────────────────────────

export interface RegisterPayload {
  managerUrl: string;
  agentName: string;
  registerSecret: string;
}

/**
 * Persisted credentials stored in `.agent-credentials`.
 *
 * - `agentKey` — generated by the agent once; used for dedup on
 *   re-registration (the manager stores this as `agent_key`).
 * - `id` — manager-assigned primary key.
 * - `token` — manager-assigned API token.
 */
export interface AgentCredentials {
  agentKey: string;
  id: string;
  token: string;
}

// ─── Registration logic ─────────────────────────────────────────

/** Decode a base64 register string. */
export function decodeRegisterString(b64: string): RegisterPayload {
  const json = Buffer.from(b64, 'base64').toString('utf-8');
  return JSON.parse(json) as RegisterPayload;
}

/** Path to the credentials file in the data directory. */
function credentialsPath(dataDir: string): string {
  return join(dataDir, '.agent-credentials');
}

/** Load saved credentials, if any. */
export async function loadCredentials(dataDir: string): Promise<AgentCredentials | null> {
  const file = credentialsPath(dataDir);
  if (!existsSync(file)) return null;
  try {
    const raw = await readFile(file, 'utf-8');
    return JSON.parse(raw) as AgentCredentials;
  } catch {
    return null;
  }
}

/** Persist credentials for subsequent restarts. */
export async function saveCredentials(dataDir: string, creds: AgentCredentials): Promise<void> {
  await mkdir(dataDir, { recursive: true });
  await writeFile(credentialsPath(dataDir), JSON.stringify(creds, null, 2), 'utf-8');
}

/**
 * Register this agent with the Manager.
 *
 * POSTs the agent's name and self-reported URL to the Manager. Returns
 * the assigned agent id and API token on success.
 */
export async function registerWithManager(
  managerUrl: string,
  name: string,
  registerSecret: string,
  agentBaseUrl: string,
  agentKey?: string,
): Promise<{ id: string; token: string }> {
  // Strip trailing slash from manager URL.
  const base = managerUrl.replace(/\/+$/, '');
  const url = `${base}/v1/manager/agents/register`;

  const body: Record<string, string> = {
    name,
    baseUrl: agentBaseUrl,
    registerToken: registerSecret,
  };
  // Pass the agentKey so the manager can update the existing entry
  // instead of creating a duplicate (re-registration / dedup).
  if (agentKey) body.agentKey = agentKey;

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`registration failed (${res.status}): ${text}`);
  }

  return res.json() as Promise<{ id: string; token: string }>;
}

/**
 * Run the registration flow if needed.
 *
 * Checks for saved credentials first; if they exist, returns them
 * immediately.  Otherwise, if cfg.registerString is present, decodes
 * it and registers with the Manager.  Returns null if neither
 * condition is met.
 */
export async function getOrRegisterCredentials(cfg: ServerConfig): Promise<AgentCredentials | null> {
  // 1. Load any previously-saved credentials.
  const saved = await loadCredentials(cfg.dataDir);

  // 2. If a register string is present, always re-register (the manager
  //    may need an updated URL or token).  Pass the agentKey for dedup.
  if (cfg.registerString) {
    // Either use the saved agentKey or generate a fresh one.
    const agentKey = saved?.agentKey ?? randomUUID();
    const payload = decodeRegisterString(cfg.registerString);
    const agentBaseUrl = `http://${cfg.host}:${cfg.port}`;
    const creds = await registerWithManager(
      payload.managerUrl,
      payload.agentName,
      payload.registerSecret,
      agentBaseUrl,
      agentKey,
    );
    // Persist (possibly updated) credentials — keep the same agentKey.
    await saveCredentials(cfg.dataDir, { agentKey, id: creds.id, token: creds.token });
    return { agentKey, id: creds.id, token: creds.token };
  }

  // 3. No register string — use saved credentials if available.
  if (saved) return saved;

  return null;
}
