/**
 * Agent CRUD routes.
 *
 *   GET    /manager/agents             → list registered agents (no tokens)
 *   POST   /manager/agents             → register a new agent (manual)
 *   DELETE /manager/agents/:id         → unregister an agent
 *   POST   /manager/agents/register    → agent self-registration (public)
 *
 * Self-registration is public (no session required) because the agent
 * carries the base64 payload generated by the authenticated admin from the
 * onboarding UI. The network boundary is the security perimeter — the
 * manager should not be exposed to the public internet without a reverse
 * proxy / firewall in front.
 *
 * The browser-facing list deliberately omits the agent's own token — the
 * proxy uses it from the manager_sessions side and the browser has no
 * business knowing it.
 *
 * Onboarding flow (admin is already authenticated in the UI):
 *   1. Admin hits "Generate registration command".
 *   2. UI builds base64(json({managerUrl, agentName})) and shows
 *      the install + start one-liner.
 *   3. Agent decodes the string and POSTs to /register with
 *      { name, baseUrl, agentKey }. No shared secret or ticket needed.
 *   4. Manager registers the agent (or updates existing by agentKey),
 *      returns {id, token}.
 */

import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { Storage } from '../storage.js';

const AddAgentSchema = z.object({
  name: z.string().min(1),
  baseUrl: z.string().url(),
  token: z.string().min(1),
});

const RegisterAgentSchema = z.object({
  name: z.string().min(1),
  baseUrl: z.string().url(),
  /** Agent's persistent key — sent on re-registration for dedup. */
  agentKey: z.string().optional(),
});

export function registerAgentRoutes(app: FastifyInstance, storage: Storage): void {
  app.get('/manager/agents', async (_req, reply) => {
    const agents = storage.listAgents();
    return reply.code(200).send(
      agents.map((a) => ({
        id: a.id,
        name: a.name,
        baseUrl: a.baseUrl,
        enabled: a.enabled,
        createdAt: a.createdAt,
      })),
    );
  });

  app.post('/manager/agents', async (req, reply) => {
    const parsed = AddAgentSchema.safeParse(req.body);
    if (!parsed.success) {
      return reply.code(400).send({
        error: { code: 'invalid_request', message: parsed.error.message },
      });
    }
    const { id } = storage.addAgent(
      parsed.data.name,
      parsed.data.baseUrl,
      parsed.data.token,
    );
    return reply.code(201).send({ id });
  });

  // ── Self-registration (public) ──────────────────────────────────
  app.post('/manager/agents/register', async (req, reply) => {
    const parsed = RegisterAgentSchema.safeParse(req.body);
    if (!parsed.success) {
      return reply.code(400).send({
        error: { code: 'invalid_request', message: parsed.error.message },
      });
    }

    const { id, token } = storage.registerAgent(
      parsed.data.name,
      parsed.data.baseUrl,
      parsed.data.agentKey,
    );
    return reply.code(201).send({ id, token });
  });

  app.delete<{ Params: { id: string } }>(
    '/manager/agents/:id',
    async (req, reply) => {
      const agent = storage.getAgent(req.params.id);
      if (!agent) {
        return reply.code(404).send({
          error: { code: 'not_found', message: 'agent not found' },
        });
      }
      storage.deleteAgent(req.params.id);
      return reply.code(200).send({ ok: true });
    },
  );
}
